-- title:   sprite_3
-- author:  josegamestest
-- desc:    teste trabalho com sprites
-- site:    josegamestest.com.br
-- license: MIT License (change this to your license of choice)
-- version: 0.1
-- script:  lua 
